Lesson 7
Irina-pi/if-js pull request #11
Opened 2022-11-03 23:45 UTC by Irina-pi

2022-11-04 17:36 UTC, 5tronciy requested changes
We agreed that you would watch what you push to the remote repo. And I am sure you know how to delete node_modules. Do it before improving deepEqual().

2022-11-04 17:36 UTC, 5tronciy commented on main.js
> +console.log(deepEqual(obj1, obj3));
deepEqual({a: 'a', b: {a: 'a' }}, {a: 'a', b: {b: 'b' }}) returns true.

2023-01-23 17:36 UTC, Irina-pi commented on main.js
> +console.log(deepEqual(obj1, obj3));
I made function deepEqual correctly

2023-01-23 22:16 UTC, 5tronciy approved these changes
Works well. Approve.

2023-01-24 04:54 UTC, merged